enclaved: fix build failure due to lack of ra.h
This commit resolves the following build failure:

In file included from stub-enclave.wolfssl/Enclave_t.c:1:0:
stub-enclave.wolfssl/Enclave_t.h:25:10: fatal error: ra.h: No such file or directory
 #include "ra.h"
          ^~~~~~

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>