rats-tls: fix build warning due to 'assert'
This commit resolves the following warning:

rats-tls/src/attesters/tdx/collect_evidence.c:39:2: warning: implicit declaration of function ‘assert’ [-Wimplicit-function-declaration]
  assert(sizeof(report_data.d) >= SHA256_HASH_SIZE);
  ^~~~~~

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>