rats-tls: sovle compilation error under openssl1.0.x env
under openssl1.0.x, there is no store.h, so it will generate
compilation error as below:
fatal error: openssl/store.h: No such file or directory

Fixes: #1290
Signed-off-by: Liang Yang <liang3.yang@intel.com>