CI/CD: avoid building shelter and inclavared packages in the nightly ubuntu SGX1 test
The patch fixes the error:
make[1]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/shelter'
make -C dist package
make[2]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/shelter/dist'
make deb
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/shelter/dist'
dpkg-buildpackage: info: source package shelter
dpkg-buildpackage: info: source version 0.6.0-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Hu Zhiming <zhiming.hu@intel.com>
 dpkg-source --before-build shelter-0.6.0
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: enclave-tls
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
cp: cannot stat '/tmp/debbuild.Qbt5/*.*deb': No such file or directory
the debs of shelter located in /root/pkgs/inclavare-containers-0.6.0
make[3]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/shelter/dist'
make[2]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/shelter/dist'
make[1]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/shelter'
make[1]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/inclavared'
make -C dist package
make[2]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/inclavared/dist'
make deb
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: Entering directory '/root/pkgs/inclavare-containers-0.6.0/inclavared/dist'
Error: Rust is not installed. Please type the "curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; source $HOME/.cargo/env" command to install Rust firstly
make[3]: *** [deb] Error 1
Makefile:20: recipe for target 'deb' failed
make[3]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/inclavared/dist'
make[2]: *** [package] Error 2
Makefile:25: recipe for target 'package' failed
make[2]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/inclavared/dist'
make[1]: *** [package] Error 2
Makefile:155: recipe for target 'package' failed
make[1]: Leaving directory '/root/pkgs/inclavare-containers-0.6.0/inclavared'
make: *** [package] Error 1

Signed-off-by: Yilin Li <YiLin.Li@linux.alibaba.com>