libenclave/attestation: fix build failure due to missing sgx_attributes.h
In file included from /usr/include/sgx_qve_header.h:35:0,
                 from /usr/include/sgx_dcap_quoteverify.h:41,
                 from libenclave/attestation/internal/sgx/dcap/qvl.go:9:
/usr/include/sgx_key.h:43:10: fatal error: sgx_attributes.h: No such file or directory
 #include "sgx_attributes.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:32: recipe for target 'rune' failed
make: *** [rune] Error 2

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>